import { useEffect, useRef, useState, type ReactNode } from "react";
import { ArrowDownRight, ArrowLeft, ArrowRight, Menu as MenuIcon, X } from "lucide-react";
import { Link, useLocation } from "wouter";
import { factoryConfig, flavors, galleryItems, processSteps, products } from "@/data/factory";

type RevealProps = { children: ReactNode; className?: string; delay?: number };
function Reveal({ children, className = "", delay = 0 }: RevealProps) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const node = ref.current;
    if (!node) return;
    const observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) { node.classList.add("is-visible"); observer.unobserve(node); }
    }, { threshold: .12 });
    observer.observe(node);
    return () => observer.disconnect();
  }, []);
  return <div ref={ref} className={`reveal ${delay ? `reveal-delay-${delay}` : ""} ${className}`}>{children}</div>;
}

function Cursor() {
  const dot = useRef<HTMLDivElement>(null); const label = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const move = (event: MouseEvent) => { if (dot.current) { dot.current.style.left = `${event.clientX}px`; dot.current.style.top = `${event.clientY}px`; } if (label.current) { label.current.style.left = `${event.clientX}px`; label.current.style.top = `${event.clientY}px`; } };
    const labels = (event: MouseEvent) => { const value = (event.target as HTMLElement).closest<HTMLElement>("[data-cursor]")?.dataset.cursor ?? ""; if (label.current) { label.current.textContent = value; label.current.style.opacity = value ? "1" : "0"; } };
    window.addEventListener("mousemove", move); window.addEventListener("mouseover", labels);
    return () => { window.removeEventListener("mousemove", move); window.removeEventListener("mouseover", labels); };
  }, []);
  return <><div className="cursor-dot" ref={dot} /><div className="cursor-label" ref={label} style={{ opacity: 0 }} /></>;
}

function BrandLogo({ compact = false }: { compact?: boolean }) {
  return <Link href="/" className={`brand-lockup ${compact ? "compact" : ""}`} aria-label="Yuva Factory home">
    <svg className="brand-mark" viewBox="0 0 42 42" aria-hidden="true">
      <path d="M7 6c3 0 5 2 5 5v11c0 4 2 6 6 6s6-2 6-6V11c0-3 2-5 5-5h6v19c0 9-7 15-17 15S7 34 7 25V6Z" fill="none" stroke="currentColor" strokeWidth="2.4" />
      <path d="M15 9v13M21 9v10M27 9v7" stroke="var(--lime)" strokeWidth="1.6" strokeLinecap="round" />
    </svg>
    {!compact && <span className="brand-name"><strong>YUVA</strong><i>FACTORY</i></span>}
  </Link>;
}

function Nav() {
  const [location] = useLocation(); const [scrolled, setScrolled] = useState(false); const [hidden, setHidden] = useState(false); const [open, setOpen] = useState(false); const previousY = useRef(0);
  useEffect(() => { const handler = () => { const y = window.scrollY; setScrolled(y > 28); setHidden(y > previousY.current && y > 120); previousY.current = y; }; window.addEventListener("scroll", handler, { passive: true }); return () => window.removeEventListener("scroll", handler); }, []);
  const links = [["Flavors", "/flavors"], ["Products", "/products"], ["Factory", "/factory"], ["About", "/about"], ["Quality", "/quality"], ["Gallery", "/gallery"]];
  return <>
    <header className={`site-nav ${scrolled ? "scrolled" : ""} ${hidden ? "hidden-nav" : ""}`}><BrandLogo /><nav className="nav-links" aria-label="Primary navigation">{links.map(([label, href]) => <Link key={href} href={href} aria-current={location === href ? "page" : undefined}>{label}</Link>)}</nav><Link className="nav-cta" href="/contact">Contact <ArrowDownRight size={14} /></Link><button className="menu-toggle" onClick={() => setOpen(true)} aria-label="Open menu"><MenuIcon size={23} /></button></header>
    {open && <div className="mobile-overlay"><div className="mobile-top"><BrandLogo compact /><button className="menu-toggle" onClick={() => setOpen(false)} aria-label="Close menu"><X size={26} /></button></div><nav className="mobile-links">{links.map(([label, href]) => <Link href={href} key={href} onClick={() => setOpen(false)}>{label}</Link>)}<Link className="mobile-reserve" href="/contact" onClick={() => setOpen(false)}>Contact Yuva Factory <ArrowDownRight size={20} /></Link></nav><div className="mobile-foot"><span>Ice cream manufacturing</span><span>India</span></div></div>}
  </>;
}

function FrostBand() { return <div className="frost-band"><div className="frost-marquee">{Array.from({ length: 2 }).map((_, i) => <span key={i}>Cold crafted <span>India</span> Built for the next scoop <span>Milk / Fruit / Fire</span> Ice cream, made with purpose</span>)}</div></div>; }

function Hero() {
  return <section className="hero"><div className="hero-media" style={{ backgroundImage: `url(${factoryConfig.heroImage})` }} /><div className="hero-cold" /><div className="hero-content"><div className="hero-kicker eyebrow">India · Ice cream manufacturing</div><h1 className="display hero-title">Made<br /><em>to</em> move.</h1><div className="hero-subrow"><p className="hero-intro">A cinematic look inside the cold, bright world of YUVA FACTORY — where ingredients, machines, and imagination become the next scoop.</p><a className="scroll-cue" href="#inside">Enter the factory</a></div></div><div className="hero-index eyebrow mono">01 / 05</div></section>;
}

function PackageStage() {
  return <section id="inside" className="section section-dark product-stage"><Reveal className="product-stage-copy"><div className="eyebrow" style={{ color: "var(--lime)" }}>Scene 01 · Product reveal</div><h2 className="display">Built for the<span>next scoop.</span></h2><p className="section-copy">We treat ice cream like a material. Folded, frozen, tested, and made ready for the moment the lid comes off.</p><Link className="lime-button" style={{ marginTop: 34 }} href="/products">Explore products <ArrowRight size={15} /></Link></Reveal><Reveal className="product-orbit" delay={1}><div className="cold-vapor" /><div className="orbit-ring" /><div className="package" data-cursor="ROTATE" aria-label="Yuva Factory vanilla package" /><div className="package-shadow" /></Reveal></section>;
}

function MacroSection() {
  return <section className="section section-ice"><div className="macro-grid"><Reveal className="macro-stack"><img src={flavors[2].image} alt="Fresh strawberry texture" loading="lazy" /><img src={flavors[3].image} alt="Ripe mango ingredient" loading="lazy" /></Reveal><Reveal className="macro-copy" delay={1}><div className="eyebrow">Scene 02 · Ingredient laboratory</div><h2 className="display">Texture<span>is flavor.</span></h2><p className="section-copy">Bright fruit. Deep cocoa. The floral pull of vanilla. Every flavor starts as a close-up — a color, a scent, a little electricity.</p><div className="tech-notes"><div className="tech-note"><strong>Cold-set</strong><span>Slow texture, clean finish.</span></div><div className="tech-note"><strong>Real fruit</strong><span>Picked for character.</span></div><div className="tech-note"><strong>Low drama</strong><span>Nothing artificial in the feeling.</span></div></div></Reveal></div></section>;
}

function FlavorSection() {
  return <section className="section section-blue"><div className="flavor-header"><div><div className="eyebrow" style={{ color: "var(--lime)" }}>Scene 03 · Flavor experience</div><h2 className="display">Meet the moods.</h2></div><Link className="scroll-cue" href="/flavors">Open all flavors <ArrowRight size={15} /></Link></div><div className="flavor-rail">{flavors.map((flavor) => <Link href={`/flavors/${flavor.id}`} className="flavor-panel" key={flavor.id} data-cursor="EXPLORE"><img src={flavor.image} alt={`${flavor.name} ice cream`} loading="lazy" /><div className="flavor-meta"><div className="eyebrow"><span className="flavor-dot" style={{ background: flavor.color }} />Flavor 0{flavors.indexOf(flavor) + 1}</div><h3 className="display">{flavor.name}</h3><p>{flavor.detail}</p></div></Link>)}</div></section>;
}

function ProcessSection() {
  return <section className="section section-dark"><div className="process-layout"><Reveal className="process-title"><div className="eyebrow" style={{ color: "var(--lime)" }}>Scene 04 · Manufacturing</div><h2 className="display">How we make<span>the cold.</span></h2><p className="section-copy">A real process, built around restraint. Twelve steps from ingredient selection to a product ready for distribution.</p></Reveal><div className="process-list">{processSteps.map((step, index) => <Reveal key={step.number} delay={index % 3}><article className="process-item"><div className="process-number eyebrow mono">{step.number}</div><div><h3 className="display">{step.name}</h3><p>{step.detail}</p></div><img src={step.image} alt={step.name} loading="lazy" /></article></Reveal>)}</div></div></section>;
}

function AboutBand() { return <section className="section section-ice about-split"><Reveal><div className="eyebrow">Scene 05 · About Yuva Factory</div><h2 className="display">Young<br /><span>at heart.</span></h2><p className="section-copy" style={{ marginTop: 32 }}>We’re building an ice cream company for people who want more from the freezer aisle: better ingredients, clearer choices, and a little more possibility.</p><Link className="lime-button" style={{ marginTop: 34 }} href="/about">Our story <ArrowRight size={15} /></Link></Reveal><Reveal className="about-image" delay={1}><img src={factoryConfig.factoryImage} alt="Stainless steel machinery in a modern food factory" loading="lazy" /></Reveal></section>; }

function FinalSection() { return <section className="section section-blue final"><div className="final-products" /><Reveal className="final-content"><div className="eyebrow" style={{ color: "var(--lime)" }}>Freeze frame</div><h2 className="display">Ice cream,<br /><span>made with purpose.</span></h2><Link className="lime-button" href="/products">Explore products <ArrowDownRight size={15} /></Link></Reveal></section>; }

function PageHero({ eyebrow, title, image }: { eyebrow: string; title: ReactNode; image: string }) { return <section className="page-hero" style={{ backgroundImage: `url(${image})` }}><Reveal><div className="eyebrow" style={{ color: "var(--lime)" }}>{eyebrow}</div><h1 className="display">{title}</h1></Reveal></section>; }

function ProductsPage() { const [category, setCategory] = useState("ALL"); const categories = ["ALL", "CUPS", "CONES", "TUBS", "STICKS"]; const shown = category === "ALL" ? products : products.filter((product) => product.category === category); return <main><PageHero eyebrow="Product showcase" title={<>The freezer<br /><em>aisle, re-cut.</em></>} image={products[2].image} /><section className="section section-dark page-content"><div className="menu-tabs" style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>{categories.map((item) => <button key={item} className={`menu-tab ${category === item ? "active" : ""}`} style={{ color: "var(--ice)", borderColor: "var(--line)" }} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="product-grid">{shown.map((product, index) => <Reveal key={product.slug} delay={index % 3}><Link href={`/products/${product.slug}`} className="catalog-panel" data-cursor="EXPLORE"><img src={product.image} alt={product.name} loading="lazy" /><div className="catalog-meta"><div><div className="eyebrow" style={{ color: product.accent }}>YUVA / {product.category}</div><h3 className="display">{product.name}</h3><p>{product.description}</p></div><span className="catalog-pack">{product.pack}</span></div></Link></Reveal>)}</div></section><FinalSection /></main>; }

function FlavorsPage() { return <main><PageHero eyebrow="Flavor laboratory" title={<>Follow the<br /><em>flavor.</em></>} image={flavors[2].image} /><section className="section section-ice page-content"><div className="section-intro"><Reveal><div className="eyebrow">A palette in motion</div><p className="section-copy" style={{ marginTop: 24 }}>From bright Alphonso mango to slow dark cocoa, each flavor is designed as a complete sensory world.</p></Reveal><Reveal delay={1}><div className="flavor-rail" style={{ paddingTop: 0, flexWrap: "wrap", overflow: "visible" }}>{flavors.map((flavor) => <Link href={`/flavors/${flavor.id}`} className="flavor-panel" style={{ flexBasis: "min(29vw, 360px)", minHeight: 470 }} key={flavor.id} data-cursor="EXPLORE"><img src={flavor.image} alt={flavor.name} /><div className="flavor-meta"><div className="eyebrow"><span className="flavor-dot" style={{ background: flavor.color }} />{flavor.id}</div><h3 className="display">{flavor.name}</h3><p>{flavor.detail}</p></div></Link>)}</div></Reveal></div></section><FinalSection /></main>; }

function FactoryPage() { return <main><PageHero eyebrow="The factory" title={<>Behind<br /><em>the cold.</em></>} image={factoryConfig.factoryImage} /><section className="section section-dark"><div className="process-layout"><Reveal className="process-title"><div className="eyebrow" style={{ color: "var(--lime)" }}>A modern food facility</div><h2 className="display">Precision<br /><span>with feeling.</span></h2><p className="section-copy">Stainless steel, controlled temperatures, and people who know exactly when to leave a mixture alone.</p></Reveal><div className="process-list">{processSteps.map((step, index) => <Reveal key={step.number} delay={index % 3}><article className="process-item"><div className="process-number eyebrow mono">{step.number}</div><div><h3 className="display">{step.name}</h3><p>{step.detail}</p></div><img src={step.image} alt={step.name} loading="lazy" /></article></Reveal>)}</div></div></section><FinalSection /></main>; }

function AboutPage() { return <main><PageHero eyebrow="About Yuva Factory" title={<>Make room<br /><em>for more.</em></>} image={factoryConfig.factoryImage} /><section className="section section-ice"><div className="story-grid"><Reveal className="story-image"><img src={factoryConfig.heroImage} alt="Ice cream product in a cold blue environment" /></Reveal><div className="story-list">{[{ n: "01", h: "Our story", p: "Yuva means young. Not an age — a way of looking at the world: curious, generous, and never finished." }, { n: "02", h: "Our values", p: "We make decisions in the open: ingredient first, process honest, and energy directed at what matters." }, { n: "03", h: "Our vision", p: "To make the freezer aisle feel like the start of something, not the end of a meal." }].map((item, index) => <Reveal key={item.n} delay={index % 3}><article className="story-item"><div className="eyebrow" style={{ color: "var(--cocoa)" }}>{item.n}</div><h3 className="display">{item.h}</h3><p>{item.p}</p></article></Reveal>)}</div></div></section><FinalSection /></main>; }

function GalleryPage() { const [selected, setSelected] = useState<typeof galleryItems[number] | null>(null); useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") setSelected(null); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []); return <main><PageHero eyebrow="Gallery" title={<>Inside the<br /><em>world.</em></>} image={galleryItems[0].image} /><section className="section section-dark page-content"><div className="gallery-grid">{galleryItems.map((item, index) => <Reveal key={item.label} delay={index % 3}><figure className={`gallery-item ${item.size}`} data-cursor="VIEW" onClick={() => setSelected(item)}><img src={item.image} alt={item.label} loading="lazy" /><figcaption>{item.label}</figcaption></figure></Reveal>)}</div></section>{selected && <div className="lightbox" role="dialog" aria-modal="true" aria-label={selected.label} onClick={() => setSelected(null)}><button className="lightbox-close" onClick={() => setSelected(null)} aria-label="Close image"><X size={26} /></button><img src={selected.image} alt={selected.label} onClick={(event) => event.stopPropagation()} /></div>}<FinalSection /></main>; }

function ContactPage() { const [submitted, setSubmitted] = useState(false); return <main><PageHero eyebrow="Contact Yuva Factory" title={<>Let’s make<br /><em>something cold.</em></>} image={factoryConfig.factoryImage} /><section className="section section-dark"><div className="form-layout"><Reveal><div className="eyebrow" style={{ color: "var(--lime)" }}>For distribution, wholesale, and business enquiries</div><h2 className="display">The line<br /><span>is open.</span></h2><p className="section-copy">Tell us what you are building. We’ll get back to you with the right flavor of answer.</p></Reveal><Reveal className="form" delay={1}>{submitted ? <div style={{ paddingTop: 40 }}><div className="eyebrow" style={{ color: "var(--lime)" }}>Message received</div><h3 className="display" style={{ fontSize: "clamp(3rem, 6vw, 6rem)", lineHeight: .84, margin: "24px 0" }}>We’ll be<br />in touch.</h3><button className="form-submit" onClick={() => setSubmitted(false)}>Send another <ArrowRight size={15} /></button></div> : <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><div className="form-row"><div className="form-field"><label htmlFor="name">Name</label><input id="name" required placeholder="Your name" /></div><div className="form-field"><label htmlFor="email">Email</label><input id="email" type="email" required placeholder="you@company.com" /></div></div><div className="form-field"><label htmlFor="interest">I’m reaching out about</label><select id="interest" defaultValue="Distribution"><option>Distribution</option><option>Wholesale</option><option>Business enquiry</option><option>Something else</option></select></div><div className="form-field"><label htmlFor="message">Message</label><input id="message" required placeholder="Tell us a little more" /></div><button className="form-submit" type="submit">Send enquiry <ArrowDownRight size={15} /></button></form>}</Reveal></div></section><FinalSection /></main>; }

function QualityPage() { return <main><PageHero eyebrow="Quality" title={<>Good inputs.<br /><em>Great texture.</em></>} image={flavors[4].image} /><section className="section section-ice"><div className="macro-grid"><Reveal className="macro-stack"><img src={flavors[0].image} alt="Vanilla ingredient" /><img src={flavors[1].image} alt="Chocolate ingredient" /></Reveal><Reveal className="macro-copy" delay={1}><div className="eyebrow">The Yuva standard</div><h2 className="display">Nothing<span>to hide.</span></h2><p className="section-copy">We care about what goes in, how it moves through the factory, and how it arrives with you. Ingredient quality, hygiene, and cold-chain discipline are part of the recipe.</p><div className="tech-notes"><div className="tech-note"><strong>Ingredient first</strong><span>Flavor starts at the source.</span></div><div className="tech-note"><strong>Food safe</strong><span>Clean rooms, clear standards.</span></div><div className="tech-note"><strong>Cold chain</strong><span>Cold from line to freezer.</span></div></div></Reveal></div></section><FinalSection /></main>; }

function ProductDetail({ slug }: { slug: string }) { const product = products.find((item) => item.slug === slug) ?? products[0]; return <main><PageHero eyebrow={`Product / ${product.category}`} title={<>{product.name.split(" /")[0]}<br /><em>{product.name.split(" /")[1] ?? "ice cream"}.</em></>} image={product.image} /><section className="section section-dark product-stage"><Reveal className="product-stage-copy"><div className="eyebrow" style={{ color: product.accent }}>YUVA / {product.category}</div><h2 className="display">A closer<span>look.</span></h2><p className="section-copy">{product.description} A considered balance of texture, flavor, and finish.</p><p className="eyebrow" style={{ color: "var(--lime)", marginTop: 34 }}>{product.pack}</p><Link className="lime-button" style={{ marginTop: 34 }} href="/products">Back to products <ArrowLeft size={15} /></Link></Reveal><Reveal className="product-orbit" delay={1}><div className="cold-vapor" /><div className="orbit-ring" /><div className="package" style={{ background: `linear-gradient(103deg,#dce7e0 0 8%,${product.accent} 8% 17%,#071014 17% 75%,#caff3d 75% 81%,#dce7e0 81%)` }} /><div className="package-shadow" /></Reveal></section><FinalSection /></main>; }

function Footer() { return <footer className="footer"><div className="footer-grid"><div><div className="eyebrow" style={{ color: "var(--lime)" }}>Yuva Factory</div><h2 className="display footer-title">Cold craft.<br />Bright flavor.<br /><span style={{ color: "var(--lime)" }}>Next energy.</span></h2></div><div className="footer-column"><div className="eyebrow">Explore</div><Link href="/flavors">Flavors</Link><Link href="/products">Products</Link><Link href="/factory">Factory</Link><Link href="/about">About</Link></div><div className="footer-column"><div className="eyebrow">Inside</div><Link href="/quality">Quality</Link><Link href="/gallery">Gallery</Link><Link href="/contact">Contact</Link></div><div className="footer-column"><div className="eyebrow">Connect</div><span>{factoryConfig.location}</span><span>{factoryConfig.phone}</span><a href={`mailto:${factoryConfig.email}`}>{factoryConfig.email}</a></div></div><div className="footer-bottom"><span>© 2026 YUVA FACTORY</span><span>Ice cream, made with purpose.</span></div></footer>; }

function HomePage() { return <main><Hero /><FrostBand /><PackageStage /><MacroSection /><FlavorSection /><ProcessSection /><AboutBand /><FinalSection /></main>; }

export default function Site() { const [location] = useLocation(); useEffect(() => { window.scrollTo({ top: 0, behavior: "instant" as ScrollBehavior }); }, [location]); let page: ReactNode = <HomePage />; if (location === "/flavors") page = <FlavorsPage />; else if (location === "/products") page = <ProductsPage />; else if (location.startsWith("/products/")) page = <ProductDetail slug={location.split("/")[2]} />; else if (location === "/factory") page = <FactoryPage />; else if (location === "/about") page = <AboutPage />; else if (location === "/quality") page = <QualityPage />; else if (location === "/gallery") page = <GalleryPage />; else if (location === "/contact") page = <ContactPage />; return <div className="site-shell grain"><Nav /><Cursor />{page}<Footer /></div>; }
